### ISSUE TITLE
Privacy Policy Update

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#1]
We should have Dechert review privacy policy and then make sure it gets online.

**Comment by RyanNovas** [comment]
Should have a phone call with Thomas Cochriel on Thursday.

**Comment by RyanNovas** [comment]
Spoke with Thomas. They want to help but first must verify that it is within the initial scope of agreement. We should hear back by September 7.

**Comment by RyanNovas** [comment]
Wrote follow up email to Thomas Cochriel.

**Comment by RyanNovas** [comment]
Meeting scheduled for 2 PM, Sept 18.

**Comment by RyanNovas** [comment]
Meeting went well. They asked me a number of questions and said they would get back in touch with more info.

**Comment by petergault** [comment]
Important info from EdSurge regarding COPPA - this covers all of the points we need to hit: 

https://www.edsurge.com/n/2014-09-30-6-questions-districts-should-ask-companies-to-protect-student-data

**Comment by RyanNovas** [comment]
Privacy policy is here: https://drive.google.com/open?id=1QS0J1ZZNIIXTc3EAO7skD8mlnH6Pgw1-1cSqPjVNcbc&authuser=0

and ready to go. 

We need to get it online, then add a link within the header or footer.

**Comment by RyanNovas** [comment]
Let's get this live ASAP. Not only is its absence somewhat of a liability, but is pointless for us to have used so much of Decherts and our own time and just have this sitting in drive. I think we should put it in the footer like this
![quill org interactive writing and grammar](https://cloud.githubusercontent.com/assets/6655439/4722366/7efeaa90-593f-11e4-9f05-368a24f99633.png)

**Comment by petergault** [comment]
Have Josh add this. It should state privacy policy & terms of service, where tos links to that page.

To get started copy the toss page and input the content. You can do this on GitHub.

**Comment by RyanNovas** [comment]
live at quill.org/privacy
