### ISSUE TITLE
Assets for Conference

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#104]
Must have
- [x] A set of tee-shirts, can just be a print of 4. 
- [x] A 6 x 7 inch card that contains a list of all of our apps on one side and a section of info about us on the other. 
- [x] Business cards. 
- [x] A single power point page. 

Nice to have
- [x] Cardboard flags that draw attention to each table. 
- [ ] a printed table cloth: http://www.table-cover.com/table-cover-styles/table-throws/
- [ ] A set of stickers for Quill and the individual apps.

**Comment by petergault** [comment]
### Postcard Front

v1:
https://docs.google.com/a/quill.org/drawings/d/1Yxl2OO2m5eZPaWMdYJF0WbeFUw5CZtbxRv0WcDHcbEM/edit

v2:
https://docs.google.com/drawings/d/1144qQpqcw27y4-xZUywSmBk8CwSzlqrAkJJwVyijvDw/edit?usp=sharing

v3: 
https://docs.google.com/a/quill.org/drawings/d/16oskvAuqHlI2-ZuBESssKiEtLAi061CeMRSz_64ispE/edit

*\* Question 1 - Box Formatting?**
Right now the boxes are probably too wide and not long enough. 

**Question 2 - What Copy should we use?**
We also need to really think about the copy here. We might want to try a few different takes. 

**Question 3 - The Call to action**
In v1 each app has a separate link, and this is kind of confusing. in v3 the call to action is moved to the bottom.

**Comment by petergault** [comment]
### Postcard Back

We could leave the back side blank. However, there are some important details we could try to include. The key thing is that we'd have to limit the whole page to perhaps 5 sentences at the most. 

Key details
1. It is entirely free
2. Sign up at Quill.org/signup

Optional:
- We are a nonprofit
- This is being built by a community, see the community at community.quill.org
- See a demo account at: quill.org/demo (or something like that, this hasn't been set up yet). 
- Browse all of our activities at quill.org/activities
- Our active learning philosophy
- Teachers can soon create their own activities.
- Social proof: best apps of 2014 by Graphite. 
- contact info: our twitter, our email + phone number for contact
- who built these lessons?

**Comment by tomcalabrese** [comment]
Question 3 - The Call to action
In v1 each app has a separate link, and this is kind of confusing. in v3 the call to action is moved to the bottom.
@petergault I would either make it so all of the links to the apps are consistent. So writer.quill.org, shuffle.quill.org, proofreader.quill.org, grammar.quill.org - quill.org/writer, quill.org/shuffle, quill.org/proofreader, quill.org/grammar.

Or I would do what you showed in v3 where the CTA is quill.org/apps

But I think it's important that we do get a link naming structure down like writer.quill.org even if we are having quill.org/apps. This will make us seem more trusted, and together.

**Comment by petergault** [comment]
Tagline: Tell your own stories. 

For Free
All of our apps and activities are free. 

Open Source Community 
Quill is built by a community of contributors. 
Show a link + arrow to community.quill.org

Signup 
Start learning today with with Quill.org

Contact info:
twitter: Quill_Grammar
email: hello@quill.org
number: (646) 820-7136

**Comment by tomcalabrese** [comment]
Powerpoint:
-16x19 

Quill logo
4 apps and titles

Quill.org

**Comment by tomcalabrese** [comment]
Business cards: https://drive.google.com/folderview?id=0BxnurkJj9VglMGVsOHBKLTFEQmM&usp=sharing

They are print ready PDFs. Let me know if you need me to separate the front and back for vista print.

## 

Postcard: https://drive.google.com/folderview?id=0B1RagCbDewKWRUFwRmxVMjJJUVk&usp=sharing

It's print ready PDF. Let me know if you need me to separate the front and back for vista print. 

@petergault @RyanNovas
