### ISSUE TITLE
OER Collaborative - Due Feb 20th

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#113]
A new fund of $12 million fund has been announced for OER materials. This is a perfect chance for us to own the language standards and receive some serious money. 

http://k12oercollaborative.org/rfp/

**Comment by matthewcoxatquill** [comment]
For this grant we need to register under a Creative Commons licence which we can find here http://creativecommons.org/choose/ . We should might also want to register for the webinar that will occur Wed, Dec 3, 2014 1:00 PM - 2:00 PM EST https://attendee.gotowebinar.com/register/120837209;jsessionid=abcwOeVVnYsKDfGJyP4Nu
