### ISSUE TITLE
update codemontage links to the various repos

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#116]
link to quill writer, quill grammar, and the community page.

**Comment by RyanNovas** [comment]
@petergault, where are these links?

On Mon, Dec 1, 2014 at 3:23 PM, Peter Gault notifications@github.com
wrote:

> link to quill writer, quill grammar, and the community page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/empirical-org/organization/issues/116.

## 

Ryan Novas
Director of Operations

Quill: Interactive Grammar
_Learn English grammar by writing sentences and proofreading passages._
http://quill.org

Connect with us on Twitter! @Quill_Grammar
https://twitter.com/Quill_Grammar

Learn more about Quill: _https://www.youtube.com/watch?v=jrl7uvD3SVk
https://www.youtube.com/watch?v=jrl7uvD3SVk_

**Comment by RyanNovas** [comment]
1. Empirical image should be changed to quill
2. Rename to Quill
3. Rename Quill project to Quill LMS
4. Rename Cofactor to Quill community and link to
5. Change to PHP from Rails

## 6. Add Quill Writer and Quill Grammar as new projects
