### ISSUE TITLE
Donations through tilt - 2 lines of code

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#117]
We can accept donations through tilt easily:
https://open.tilt.com/donations

**Comment by RyanNovas** [comment]
Let's get this set up and make a donation right away. If we get one before
December 31st, they waive the credit card/processing fees for the first 10k
in donations.

On Tue, Dec 2, 2014 at 2:49 PM, Peter Gault notifications@github.com
wrote:

> We can accept donations through tilt easily:
> https://open.tilt.com/donations
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/empirical-org/organization/issues/117.

## 

Ryan Novas
Director of Operations

Quill: Interactive Grammar
_Learn English grammar by writing sentences and proofreading passages._
http://quill.org

Connect with us on Twitter! @Quill_Grammar
https://twitter.com/Quill_Grammar

Learn more about Quill: _https://www.youtube.com/watch?v=jrl7uvD3SVk
https://www.youtube.com/watch?v=jrl7uvD3SVk_
