### ISSUE TITLE
SIBR Grants - $150k Due Jan. 15th!

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#118]
https://www.edsurge.com/n/2014-12-01-applications-open-for-150k-to-1m-grants-for-edtech-startups?utm_source=LearnLaunch+Mailing+List&utm_campaign=7b0d6ad258-12_5_2012&utm_medium=email&utm_term=0_986988f73c-7b0d6ad258-56812117

**Comment by petergault** [comment]
http://ies.ed.gov/sbir/2015solicitations.asp

**Comment by RyanNovas** [comment]
@petergault, moving forward can you add these to Google Calendar too? There's no deadline functionality in Github.

**Comment by petergault** [comment]
Grant application is done!
