### ISSUE TITLE
Intern for Educator Outreach 

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#146]
Look for intern on idealist and other sites. What are a list of sites to find interns?
Idealist
Craiglist
What else?

**Comment by petergault** [comment]
- Post to Idealist
- Get internship posted to intern match (powered through look sharp). 
  -craiglist. 
- http://www.hastac.org/opportunities/find?tid=96

**Comment by RyanNovas** [comment]
Let's hold off on posting on paid sites. It may be a bit early for summer interns and we'll be spending at least $100 per site. Posted on Intern match as they give credits, about to Tweet the internship page, and we can do an email blast about it too.

**Comment by tomcalabrese** [comment]
Indeed is a good one too because they aggregate from other sites.
