### ISSUE TITLE
Write letter of praise / thanks to Lawyer's Alliance for Stevens work

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#15]
Goal: write a 2 paragraph thank you note that details Steven's work to complete the 1023. Important details to include: 
- Close attention to detail. 
- Multiple takes. 
- Understood a variety of concerns around being a revenue driven nonprofit. 
- Handled complex issues such as loan reporting. 
- Timely and prompt feedback. 
- Overall, we're extremely thankful for the time he put into this, thankful to Dechert for support Nonprofits, and the Lawyers Alliance for connecting us. This will go to Dechert and Lawyers Alliance, and LinkedIn rec. 

It will start

> I am writing this letter in gratitude (in praise?) or Steven Lorach for the outstanding work he did to prepare our 1023 form. Steven picked up our 1023 form from James Cosgrove, who did a great job starting our application.

**Comment by RyanNovas** [comment]
Draft here: https://docs.google.com/a/quill.org/document/d/1gWYslE-7WFZKZsfvR3CDmskLPJc-0H02s1wY-V_unzc/edit?usp=sharing
