### ISSUE TITLE
Data Entry - Add Brackets to Grammar Concepts

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#156]
For this google spreadsheet, someone needs to add brackets for the grammatical term being tested for within the question. You can see from the link below that the first 40 entries have brackets in them. (**Column D.**)
- There may be questions about what should be put in brackets. For example, if the practice sentence involves commas, the user should put the entire section in brackets. For example, on a practice question about using colons in lists, it might be read. 
  > Prompt: I went shopping for the following items beans, chicken, and milk.
  > Andrew: I went shopping for the following {items:} beans, chickens, and milk.

It won't always be clear where the brackets should go. For example, it could go somewhere along the lines of {items: beans}, etc. Where the data entry person doesn't know, they should ask Peter and they will work it out together. 
- The job should take about 5-6 hours, and the pay is $100. 
- Andrew Wilcox might know people who can do data entry work. We could also ask Cody to post it to the bat haus newsletter. 
- The link to the data set: 
  https://drive.google.com/open?id=19SJ1ZHZPt-esd2A7kA-sTCCjRVAwHdVj7gNANe7CGJ4&authuser=0
- To check that the person did an accurate job, Will should write a script that tests for the following attributes:
- Each entry should have both a "{" and a "}" bracket. 
- The same number of entries should exist from the current csv to the updated one (i.e. make sure the user didn't by accidentally delete) a row, which can mess up all of the data.

**Comment by RyanNovas** [comment]
Data has been validated and is ready for upload.
