### ISSUE TITLE
Questions to prepare

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#188]
Questions to prepare for sales advice. Here is a brief summary of the questions. Please prepare as detailed version of this question as you can, going into as much detail as possible about the problems presented and possible solutions. 
1. How can we effectively work with a teacher using Quill in her classroom to create a school wide sale?

2.What can we do when a teacher expresses interest in Quill Premium but then says he is leaving next year, and the next person is less interested?

**Comment by ccowdery** [comment]
1) The best way to get a leverage a single class into a school wide sale is to have the teacher put you in contact with the purchaser. Although a single teacher might have a discretionary income of up to 200 for class supplies, they don't have the cash or the ability to approve the cash for that large of a transaction. So use the teacher to find out who the purchaser would be, A good way to phrase this question would be:
 "Who would need to sign off on this before we get started?"

Once you are in the room with the purchaser for the school, you sell Quill's value and its teaching methodology*, as well as the positive experiences of the teacher who put you there. Wait for the purchaser to ask about the price, let him bring it up. 
*A note here is that I am going to look into some educational theory to get some citations as to why Quill is works according to educational theory. A teacher asked me that and I realize that while I had the neuroplasticity argument, I had no real educational theory to back up why Quill works.

Once he asks the price, use your judgement and ballpark him on a scale from $10-12/student per year. See how he reacts to the number. Don't immediately bargain the price down, but know that we are able to drop as low as $5. Ask him how many students he is looking to set up with Quill Premium, and then base your new Quote around the number of accounts that he is proposing. Once you verbally agree to the sale, stand up and shake hands,then say that you will send him an invoice for the sale.
