### ISSUE TITLE
Quill Premium ToS

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#189]
https://docs.google.com/a/quill.org/document/d/1YyTmFYg2ZTaJ3KSsbuxHu6SIu2r0XiP-DaEPiIaQvoc/edit

**Comment by RyanNovas** [comment]
Updated section here: https://docs.google.com/document/d/1F1GBDSF4OqDG-STZt9D3LZ9Gn7LAPgng5CwZxGfgIpI/edit

I don't think we should do refunds unless we terminate it. seems like a huge headache. if they push us for it, we can offer it to un-used users.

I can't find any information on 528.
