### ISSUE TITLE
Tracking 404 errors

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#191]
@RyanNovas  This is a good project when you've got a day off. You might be able to figure out how to set up google tag manager on your own or work with Hussain to get this worked out. 

We recently have seen a big spike in people hitting a 404 page. We're tracking this through Mixpanel, and yesterday we saw 2,700 hits on our 404 page. Is there a way to track, either through mixpanel or google analytics, which pages people are coming from when they hit the 404? We may be able to figure out what is causing this confusion and hopefully mitigate it. 

Here is one blog post that details a strategy: 
http://www.lunametrics.com/blog/2014/08/19/404-errors-google-analytics-google-tag-manager/

**Comment by RyanNovas** [comment]
@petergault this is the same issue as https://github.com/empirical-org/Empirical-Core/issues/687

Right?
