### ISSUE TITLE
Cancel Peak

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#2]
We were charged $300 for peak, and then charged monthly at $50. It is not worth the money, cancel it. Make sure that we actually got our money back in Wells Fargo for the $300, I never saw the money come back.

**Comment by RyanNovas** [comment]
We were credited initial payment, minus the $41 agreed per month -- that is gone. I've emailed them requesting confirmation of cancellation.

**Comment by RyanNovas** [comment]
Confirmed cancellation.

**Comment by petergault** [comment]
Ok awesome, thanks
