### ISSUE TITLE
What percentage is tablets?

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#21]
What percentage of our traffic is tablets?

**Comment by RyanNovas** [comment]
![screenshot 2014-09-10 at 10 47 20 am](https://cloud.githubusercontent.com/assets/6655439/4219415/91a59cfa-38f9-11e4-8d55-fbccc70ca2db.png)

![screenshot 2014-09-10 at 10 55 11 am](https://cloud.githubusercontent.com/assets/6655439/4219591/edbb4f7a-38fa-11e4-9779-7ac4e21f1027.png)

11.77% tablet, 7.20% mobile = 18.77% touchscreen
