### ISSUE TITLE
Prepare real sample data for Tom 

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#26]
Log into 10 teacher accounts (you can grab the accounts by going to log entries and looking at the IP to find the teacher or use google analytics to find locations and then search by location) and use that to gather the following attributes:

1) What names are teacher's creating for their classrooms? How many classrooms are they creating? How many students per classroom?
2) Which activities are teachers assigning? How many?

**Comment by RyanNovas** [comment]
https://docs.google.com/a/quill.org/spreadsheets/d/1tpK1tOtSgok2ZfSbTAjKIKlYNFriaNjkDC0qSviMT28/edit?usp=sharing
