### ISSUE TITLE
Real Data for Empirical mockups

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#27]
Here is a link to our Empirical profile pages: https://moqups.com/gault8121/Vs2vQYQE

There are three pages we need to design. 

We can try to do this with wordpress, or we could also do it with weebly or wikidot. We don't need to build the actual functionality in, we more need to build a working mockup of the site and then we will re-write it in ruby later on. 

For now the key thing is that for the team page and the profile page we need to swap the six sample entries with sample data.

**Comment by RyanNovas** [comment]
This has been completed. However, I disagree with the second sentence [name] [suggested] [idea] convention. While a good suggestion should count as a contribution, often people carry out an action without making a suggestion, so a suggestion could often be an irrelevant or nonexistent part of a tangible contribution.
