### ISSUE TITLE
Social Media Overhaul

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#29]
**Empirical Facebook**
For Empirical We want to post links to all of our blog posts. We also want to feature photos from all of our open source events. Try to grab everything from the open source events (in a photos folder). 

https://www.facebook.com/empirical.org

We will link this prominently on our empirical.org page. 

**Empirical Twitter**
We should post a couple of links to the Empirical Twitter account. 

**Quill.org Facebook account**
We should make sure that we post all of our education related photos (such as conferences and the play testing SWF with kids) on our page.

**Comment by petergault** [comment]
We also need the Twitter Account - Quill_org 

We may want to switch from Quill Grammar to Quill Org

Do we have Quill Writer?

**Comment by RyanNovas** [comment]
Underscores are not permitted as usernames. I just registered QuillOrg and we can change it if/when it is necessary.

**Comment by RyanNovas** [comment]
All photos are posted
