### ISSUE TITLE
update static text in about us page

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#3]
see the google doc.

**Comment by RyanNovas** [comment]
I've sent all relevant people a request for a brief bio and headshot. Will follow up again early next week.

**Comment by petergault** [comment]
The list of people: 
**Modify the grid to 10 entries**
The new team: Peter (Product Designer), Ryan (Operations), Josh (Developer), James (Developer), Jason (Developer), Will Laurence (Developer), Tom Calabrese (Designer),  Bill Robison (Editor),  Maggie (Activity Writer), Matt Coleman (OSS Developer)

This is ten entries, so we will need to modify the code. 

**Create Alumni Page**
Also, talk to Jason, and create a new page called quill.org/Alumni. This page will mirror the About Us page (you can copy and paste it) except it will feature profiles for the previous contributors. 

Unlike the current about us page, the copy at the top will simply read:

> We've had over 50 people contribute to Quill. Here is a partial list of our past contributors. See our current team on our About Us page. 
> The About Us should like to about us. 

**Add link to the bottom of the about us page to alumni**
Underneath the current contributors we should have a link that states:

> Click here to see our previous contributors.

**Comment by RyanNovas** [comment]
All content for this project is ready to go. We just need to find a point where there is enough downtime to throw some devs at it for an hour.
