### ISSUE TITLE
Quill.org/Impact - An infographic of our impact

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#31]
James has complied all of the stats on our current usage. We should turn these into a nice infogrpahic esque page that details our impact in say 4 charts. 

Questions to answer:
where do the students come from?
What types of schools?
Which international countries have active users?
How many classrooms?
How many students?
How many activities completed?
What's the daily traffic (it'd be cool if we could embed a live graphic showing day by day).

Subjective Part:
After we state the stats, let's round it out by posting quotes from teacher reviews we can grab from emails, twitter messages, review sites, etc. 

Future questions to add to this:
How much time have students spent?
How much time has an average active user spent?
What are our most popular activities? How many times has each of these popular activities been completed?

**Comment by RyanNovas** [comment]
piktochart.com could be a good option if we want to do this in house. Has some non-profit specials too.

**Comment by petergault** [comment]
https://drive.google.com/a/quill.org/folderview?id=0B-r431ws0zjXcVZ3SmowbnJoNHc&usp=sharing

Class-code Results Chart is the interesting one.

**Comment by RyanNovas** [comment]
Some of these questions can't be answered now. Specifically, 

What types of schools?
- We've collected virtually no data on this as the school selector is brand new.

Which international countries have active users?
- We can tell where visitors come from with analytics. We may be able to do active users if we fine tune our analytics. Alternatively, if there is a tool that can batch convert IP addresses to nations, we could probably do this in our database ourselves.
