### ISSUE TITLE
Our One Line Audit

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#36]
Boiling Quill down into one sentence is absolutely essential for telling our story. 

**When our supporters tell others what Quill is, they need to have a one sentence description that passes on what we do.**

_At the moment we have employed many different one lines. We need to commit to one line and use it everywhere._
## Quill in One Line

Quill provides writing, grammar, and vocabulary activities to middle school and high school students. 

Our mission is to build confident writers.

We make students active players in their education. 

Quill is raising writers in a digital era. 
## Empirical in One Line

Empirical is an Open Source Community building Interactive education

Empirical is a nonprofit organization creating interactive education. 
## Other Examples

_Here is a list of one liners used by other organizations. We can use these to think about our own._

Bayes Impact is bringing the power of data science to nonprofits and governments.

**Comment by petergault** [comment]
Quill is creating authors of the 21st century.

Quill is fostering writers in the internet era.

Quill is raising writers of the digital era.

Quill is fostering authors of the digital era.

Quill is fostering the authors of the 21st century.

Quill is building writers of the 21st century.

Quill is fostering writers of the digital era.

Quill is building a generation on authors.

**Comment by petergault** [comment]
@matthewcoxatquill some ideas about the one line.

**Comment by petergault** [comment]
Quill is raising writers in the digital era. 
Quill is inspiring the next generation of writers. 
Quill is creating authors of the digital era. 
Quill is inspiring writers of the digital generation. 
Quill cultivates writers for the digital era.  
Quill raises writers for the digital era. 
Quill empowers writers for the digital era. 

Should we focus on the term authors or writers?

**Comment by petergault** [comment]
@tomcalabrese  tag line list.

**Comment by petergault** [comment]
Quill empowers students to become better writers. 

Quill empowers students to become writers.

**Comment by petergault** [comment]
Quill builds the foundation of strong writers.

**Comment by matthewcoxatquill** [comment]
Quill, bring literacy to everyone, everywhere, free  and open source.

Quill,helping students to write their own story.

**Comment by matthewcoxatquill** [comment]
Quill, raising writers from the classroom to your living room, free of charge.

**Comment by tomcalabrese** [comment]
"Helping students to write their own story" has some legs to it.

**Comment by matthewcoxatquill** [comment]
Quill, no paper, no boundaries, no barriers to education.

**Comment by matthewcoxatquill** [comment]
Raising writers for a digital age.

**Comment by matthewcoxatquill** [comment]
Every student has a story and quill helps them to write it.

**Comment by matthewcoxatquill** [comment]
Quill helps writers over come the barriers to education of the past and helps them to right their future.

**Comment by matthewcoxatquill** [comment]
With Quill the worlds your classroom.

**Comment by matthewcoxatquill** [comment]
Quill, empowering students today so they can achieve tomorrow.

**Comment by petergault** [comment]
Writers for life 

Lifelong writers

Challenge the World 

Writers Deciding their future. 

Empowering writers for life. 

Setting goals for writing. 

Setting goals for writers. 

The key qualities:

Writers are setting their own direction. 

Taking hold of their own writing. 

Challenge students to write 

Engaging Every Student With Writing

**Comment by petergault** [comment]
Challenging Writers with Hands on Activities.

**Comment by petergault** [comment]
Fostering Writers with Hands on Activities.

**Comment by matthewcoxatquill** [comment]
Quill, empowering students to write their own story.

**Comment by petergault** [comment]
Quill helps students tell their own stories. 

Quill helps writers tell their own stories. 

Quill helps writers tell their own story.

**Comment by petergault** [comment]
Quill empowers students to write their own stories.

**Comment by petergault** [comment]
Quill, empowering students to write their own stories. 

Quill, empowering students to tell their own stories.
