### ISSUE TITLE
Apply for award

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#4]
@Ryannovas

New! EdTech Digest Awards
The EdTech Digest Awards Program recognizes people in and around education for outstanding contributions in transforming education through technology to enrich the lives of learners everywhere. Featuring the best and brightest in edtech, the annual recognition program seeks to highlight and celebrate the most effective products and the most innovative and inspiring people.
More information Deadline: Tuesday, September 30

**Comment by RyanNovas** [comment]
This is being put on hiatus while we figure out the design issues. We have until the end of September and it is a pretty straightforward submission.

**Comment by petergault** [comment]
@RyanNovas This deadline is coming up, we need to get this done.

**Comment by RyanNovas** [comment]
Applied
