### ISSUE TITLE
Marketing Master List - 100+ Priorities 

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#41]
This infographic lists every single task a marketer should do. There are over 100 ideas here. We should review this list and put together our own list about immediate marketing tasks we should tackle. This list should go here. 

https://drive.google.com/file/d/0B-r431ws0zjXYjBTRU9Fa1d5R00/edit?usp=sharing

**Comment by petergault** [comment]
Here are some ides to add to this list:

Google Play for Education

> an app marketplace for educationa apps. 
> Look into all the education hubs and get us listed everywhere. 

Get into the education press. 

> Teachers look to EdSurge - get onto EdSurge. 
> Find all other EdSurge like teaching locations - where do teachers go to find materials? The key to talk to teachers and find out where they look (i.e. what educational magazines do they read?). 

Donation Based Payment

> Pay what you want for Parent's accounts. Great Story. 

Library's for adult learners. 

> Get a major media story about people using grammar tools to learn. 

Create a Tech Story

> Tablets vs. laptops - through audrey watters, her contacts. 

Get the CCSS Stamp of Approval. 

> Turn this into a story, who has this?

Go to the game community. 

> Make an appeal that this is video games at its best. 
> Get the intellectual gamers community on board - bogost, etc. 

Reach out to the teaching community. 

> Go to the National English teachers convention with a story - the tablets story.  
> Have each teacher refer the product to 6 other teachers. 

Traditional Press

> Look at our rival press, contact those journalists that wrote those articles. 
> In all our press post a message in the comments board, we are here to answer questions. 

Community Management 

> Community manager manages discussions on forums, focuses feedback. 
> Solicits interviews from community members using product, other communities.

**Comment by tomcalabrese** [comment]
Also, once we have non-profit status we could apply for Amazon Smile: https://org.amazon.com/
