### ISSUE TITLE
Top Priority: Choose which Metrics we are going to track for now

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#43]
Keen is very powerful. We should gather together every metric we want to display and add it to this master list. 

This document contains a list of all of the do 

**There are two goals here:
1) Put together a master list of every question we want. 
2) Put together a lis of what we want to visualize now.**

Rather than visualize everything at once, we'll start with a batch of questions and then build out the functionality over time.

https://docs.google.com/a/quill.org/document/d/13GlhCq5fCbFlHGm30fVpi_5sJI_XPszpNOfYU9WEsns/edit

**Comment by RyanNovas** [comment]
Closing this as the immediate issue has been resolved.
