### ISSUE TITLE
Volunteer Game Designer

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#45]
We should find a game designer who would like to help us think about the game mechanics. 

Sources:
https://docs.google.com/spreadsheets/d/1P5xh1t0SOUlVmFkLKPk07DO4dWzM3B9bUWFctWEk1bY/htmlview?sle=true#gid=0

**Comment by tomcalabrese** [comment]
Are these people using Quill?

**Comment by petergault** [comment]
No this is a list of college students who are following Sam Altman's course "How to Start a Startup".  We might find some people who are interested in collaborating on our open source projects.

**Comment by tomcalabrese** [comment]
Oh, cool! Yeah we could use more eyes on the gaming functionality.

**Comment by petergault** [comment]
Places to look: 
IGDA NJ Arcade & Demo Night: September 30th, 2014
NYC Indie Games
NYU Game Center

**Comment by petergault** [comment]
Questions to Ask - How you would implement these ideas?
http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd

Which comment struck you as being significant? 
https://news.ycombinator.com/item?id=8402859

**Comment by petergault** [comment]
Sources to look at: 
https://docs.google.com/a/quill.org/forms/d/1PphSgV3JvyUOxxz5Xh2dgm2dgILXwKsFXdywQIdSRzU/viewform
https://docs.google.com/a/quill.org/forms/d/1ZGJuGLFZvFKc7LsEN0T3Bg9PvPLsZ1oTkcXklGjaCfw/viewform
IndieCade developers
Dan's Friend
Gamificaiton MOOC -> Email the creator of the group, ask if he will send out an email to the listserv. 
Post to the Gamification forum. 
- Thoughts on variations on this game. 
- Adding a competitive points mode to this for a class. 
  > Have a dedicated post about the game design role - engaging kids two possible scenarios. 

http://www.meetup.com/gamedays/
http://game-design.meetup.com/cities/us/10001/
http://education.meetup.com/cities/us/10001/
http://www.eventbrite.com/e/tableflip-a-game-design-conference-tickets-12678013279?ref=ebtnebregn
http://www.nerdwallet.com/blog/nerdscholar/2014/nerdscholar-favorites-game-design-programs/
http://www.instituteofplay.org/wp-content/uploads/2011/11/Games-Learning-Reading-List-v1-1.pdf 
http://www.meetup.com/GamesForGood/

neogaf main internet forum
gamasutra 
gamedev

who should i reach?

http://gamecenter.nyu.edu/game-designers-in-detail-lukas-litzsinger/
http://www.leagueofgamemakers.com/probability-for-game-designers/
http://stonemaiergames.com/the-top-10-things-i-learned-about-game-design-in-2013/
https://boardgamegeek.com/forum/26/boardgamegeek/board-game-design
http://www.meetup.com/Game-Makers-Guild/

http://www.bgdf.com/forums/game-creation/prototyping
http://www.bgdf.com/forums/game-creation/new-game-ideas
http://www.bgdf.com/forums/general/welcome-bgdf

http://www.bgdf.com/forum/game-design/game-design-showdown/gds-november-2014-empires-autumn

http://www.meetup.com/Game-Based-Learning-NYC/events/219203470/

http://www.nypl.org/coursera
