### ISSUE TITLE
Teacher Outreach

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#49]
Our goal is to reach out to all of our teachers and create communication via email or (hopefully) via a video chat. Our goal is to learn more about what they are interested in teaching, and how we can improve the platform. We'd also like to find out what frustrations they are having with our current product. 

As a follow up goal, we'd like to get honest feedback on 

The goal here is to listen. 

We can build relationships with teachers, and by listening to their needs we can build a product they'd like to buy. As a starting point, let's put together a list of contacts and make sure there are no duplicates.

1) Our most active classrooms by active class-codes. 
- Ryan can pull this from Keen when we are ready. There is no point in doing it before hand as it will be more accurate the later we do it.

2) All of the teachers who have emailed us. See the teacher dialogue folder. 
- Don't go back past July 9th for this part. I've already compiled the earlier ones into the teacher advocate list.

3) We have lists of teacher contacts, such as KIPP.
- https://docs.google.com/a/quill.org/spreadsheets/d/1gVkRSFya1Xp-YIxkkDJf6HjzoIe7hTL_DjgBmHKSj7I/edit?usp=sharing

4) We have contacts, such as 4.0, who can introduce us to further teachers. 

**~~5) Reach out to all of the partner schools for the pilot testing. This is a key goal.~~**
- ~~https://docs.google.com/a/quill.org/spreadsheet/ccckey=0Aur431ws0zjXdGRnRUNLVEk0UXpnYWs5MFBBVG1TOGc&usp=sharing~~

6) Reach out to dell to connect with their student voice organization. 

7) Twitter Chat list. (see issue #32 )

**Comment by petergault** [comment]
We need feedback on the following question: Would teachers prefer to use a passage that tested a variety of concepts related to a single theme (such as verbs or comma usage) or would teachers prefer to use a series of activities grouped together by the Common Core? While we will do both, it'll be helpful to receive qualitative feedback on what teachers prefer. 

What type of activities would they like to see?

**Comment by RyanNovas** [comment]
I think the main priority here should be to get in touch with the pilot schools. We had pretty abysmal engagement with the last cohort, so we should start building a relationship with this one now while their lesson plans are still flexible. Once we've gotten them signed on/using us, then we can reach out to them with questions.

**Comment by petergault** [comment]
@RyanNovas Okay yeah let's start with that. Do you want to take this info and prep a plan for pilot outreach? Basically a list of questions we want to engage them with, with the goal to be talking over a phone call or video chat. Matt can then do all of this engagement tomorrow. 

We can also point them to our user voice for more info.

**Comment by RyanNovas** [comment]
@petergault I'm writing that up right now.

**Comment by petergault** [comment]
@RyanNovas We should also really focus on the rocketship schools. We should reach out to all of them, see which teachers are on board now, find the literacy advisors, work with Maggie, etc. to make a big push with them. 

To get them on board we should share this pdf with all of them and tell them we will provide webinar professional development sessions where we walk teachers through Quill and answer questions. Many edtech products offer webinars, and it seems like a good way of building a personal relationship. 

@matthewcoxatquill

**Comment by RyanNovas** [comment]
@petergault  OK, lets do pilot then Rocket, then general teacher outreach.

**Comment by petergault** [comment]
Yep for sure. Matt's ready for outreach. Let's think about how we can track all of these projects. Perhaps we want to create a new Projects tab in gmail for 2014 Teacher Outreach. We should also clean up old gmail projects such as finding the SWF dev.

**Comment by RyanNovas** [comment]
The folder has been created and I made an archived projects one for old/inactive project folders.
