### ISSUE TITLE
Update the titles of the stories

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#5]
@RyanNovas 

The titles for these assessments are way too long and cluttered. 

![screen shot 2014-09-03 at 10 59 22 am](https://cloud.githubusercontent.com/assets/3667179/4136002/0a603d28-337b-11e4-8276-d5379fc928d1.png)

Sample text is included below. 

The key thing here is that each of the six versions of the story will be numbered 1-6. This will help teachers distinguish between the passages. All of the details will go into the description. 

Title: 
Passage Proofreading: 1. Anansi Becomes the God of Stories (Mythology)

Proofread a passage correcting eight errors in capitalization of dates and names, as well as commas in dates and lists. This passage covers Common Core concepts 1.2a. and 1.2c. This version of the passage contains hints!

Passage Proofreading: 2. Anansi Becomes the God of Stories (Mythology)

Proofread a passage correcting eight errors in capitalization of dates and names, as well as commas in dates and lists. This passage covers Common Core concepts 1.2a. and 1.2c. This version of the passage does not contain hints!

**Comment by RyanNovas** [comment]
This has been completed for the CCSS #1 parentheses passages. Will need to be reopened if/when we add the ones without hints so that we can keep them in numerical order.
