### ISSUE TITLE
Description for Seminar  - Due by October 1st!

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#53]
Great! We'll schedule you for October 22nd, then. 

In between now and then, one thing I need from you is the title of your seminar, short description of it, and brief bios of the presenters at your earliest convenience. This is so we can properly advertise it on our events calendar. 

Here are some examples that you could draw from: 
Project Ed: http://edlab.tc.columbia.edu/index.php?q=node/10992
Voxy: http://edlab.tc.columbia.edu/index.php?q=node/10853

Talk to you soon!

**Comment by RyanNovas** [comment]
@petergault how is this going? due yesterday

**Comment by RyanNovas** [comment]
@petergault is this still active? due 16 days ago.
