### ISSUE TITLE
Prepare new Teacher's Handbook

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#58]
We put together a handbook for the previous pilot, and it seemed to be popular. 

When new teachers sign up we can also send this handbook as a pdf. It is basically a 4 page cheat sheet that overviews what is going with Quill, a checklist for signing up, an overview of the user experience. The tech savy won't need it, but the less tech savy teachers may appreciate it. It's also a great document to share with other teachers, and teacher seem to enjoy having a print out they can reference. 

What we will do is automatically email this pdf out to teachers either when they sign up or afterwords. 

The raw document:
https://drive.google.com/file/d/0B-r431ws0zjXZnpCcVFGQUlFNW8/edit?usp=sharing

The pdf: 
https://drive.google.com/file/d/0B-r431ws0zjXYXdJVDQxYUpmcWM/edit?usp=sharing

**Comment by RyanNovas** [comment]
We will just need to strip out the pilot talk from the current one, then we should have a two-three page handbook.

I don't like the idea of attaching it automatically though. This is a great way to trigger spam filters.
