### ISSUE TITLE
fix links in documentation

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#6]
Documentation in the getting started section links to the old gitter chat and to the old google groups. 

Please go through everything here: https://github.com/empirical-org/Documentation

Such as in the getting started section, and update the links. 

Google groups -  https://groups.google.com/forum/#!forum/empirical-core
Gitter - gitter.im/empirical-org

**Comment by RyanNovas** [comment]
Taken care of with the exception of Documentation/Cofactor/How to Provision Cofactor, where it is written:

## 1. Google Groups Setup

Create a new google group for each forum. 

To grab the embed code, go to manage > information > general information, and copy and paste this line:
https://groups.google.com/forum/embed/?place=forum/compass-questions

@petergault do we want to change this, or let it be for the time?

**Comment by RyanNovas** [comment]
@petergault how should i deal with above comment?
