### ISSUE TITLE
Change Skillset to grade level

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#61]
Change the name of sections to grade levels. We may need to delete all of the sections and then rename grade level.

**Comment by RyanNovas** [comment]
I'm getting a 500 error when I attempt this. Creating an issue now.

On Thu, Sep 25, 2014 at 11:43 PM, Peter Gault notifications@github.com
wrote:

> Assigned #61 https://github.com/empirical-org/organization/issues/61 to
> @RyanNovas https://github.com/RyanNovas.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/empirical-org/organization/issues/61#event-170530810.

## 

Ryan Novas
Chief Operations Officer

Quill: Interactive Grammar
_Learn English grammar by writing sentences and proofreading passages._
http://quill.org

Connect with us on Twitter! @Quill_Grammar
https://twitter.com/Quill_Grammar

Learn more about Quill: _https://www.youtube.com/watch?v=jrl7uvD3SVk
https://www.youtube.com/watch?v=jrl7uvD3SVk_

**Comment by RyanNovas** [comment]
We should see if we can add an "Edit" function to this. We'll need to do something along the lines of this issue everytime we adjust the arrangement of an app, so we may as well just set it up the right way now.
