### ISSUE TITLE
Sentence Shuffle Testing Work

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#66]
For Sentence Shuffle we need to test it with a variety of content packs to see what works.

Sentence Shuffle works well for an informational text, where there is a clear structure in which the sentences should be organized. 

Goal:
Go to Newsela, Readworks, Wikipedia (simple) and other sources, and find a variety of informational texts. Plug those texts into Sentence Shuffle and then test them out.

**Comment by RyanNovas** [comment]
One quick and easy thing I would suggest is making a random or shuffle button on the review and create page. Right now, it is more "Curated Sentences in Wrong Order" rather than "Sentence Shuffle." This becomes very time consuming with longer texts.

Also, being able to select multiple items at once would be helpful. I am trying to sort a Newsela article and it is frustrating when I've grouped together four paragraphs into one paragraph and then realize all of them need to be moved up or down.

We need to find a way to show when something is out of order.  The easiest method might be grouping correct blocks of text together after submit is hit. Then only the ones that are wrong will need to be shuffled around.

**Comment by RyanNovas** [comment]
5 paragraph Essay -
http://sentenceshuffle.com/#/exercise/yWpORwKu9l

Single Paragraph - this one was easy
http://sentenceshuffle.com/#/exercise/VJflDGx1XC

To Kill a Mockingbird Timeline - shouldn't be hard if you just read the book.
http://sentenceshuffle.com/#/exercise/gPf2qxpYU2

SHSAT Sentences - Research Paper - pretty easy
http://sentenceshuffle.com/#/exercise/tDQ41Eigfb

SHSAT Sentences - Cat out of the Bag - easy
Five Paragraph Essay - this one was easy
http://sentenceshuffle.com/#/exercise/yWpORwKu9l

MLK Short Passage - Easy except for last two sentences
http://sentenceshuffle.com/#/exercise/xuQ6EM3Cdv

American Revolution - Very easy
http://sentenceshuffle.com/#/exercise/q7OHX3IkQx

Landbridge 10 paragraph passage - With hints this one is doable -- I got a 7/10 on it, but I constructed it and am not a fifth grader.
http://sentenceshuffle.com/#/exercise/fnpKq3I2N9

This one was way too hard.
Newsela 670L on Syrian Rebels - this was virtually impossible
http://sentenceshuffle.com/#/exercise/s65xTDp3rt

The use case here seems to be for forming logical/narrative structures. I don't think this will generalize well to many other literacy topics. One other potential use could be history timelines/scientific processes (e.g. put the steps of photosynthesis in their correct order).

**Comment by petergault** [comment]
### Some Sample Text from Wikipedia Simple

**Lewis and Clark Expedition**
The Lewis and Clark Expedition was an expedition by Meriwether Lewis (1774–1809) and William Clark (1770–1838), two men chosen by United States President Thomas Jefferson to explore the Louisiana Purchase, which the country had just bought from France. (This land was made up of much of what is now the Central and Western United States). They left Saint Louis in 1804, leading a group of 33 people. The group reached the Pacific in 1806, viewing much of the West on the way and writing down what they saw. **Along the way, the group was joined by a Shoshone Native American woman named Sacagawea, who helped guide them.** After their exploration, Lewis became Governor of Louisiana Territory and Clark became Governor of Missouri Territory.

_In this activity the order is essentially fixed. The one controversial statement is that "Along the way". This could come either before or after the sentence "The group reached." Perhaps we need to flag certain sentences as wild card sentences, where they can either belong to multiple spots, or they don't get don't get judged on their spot?_

**Apollo 11 Launch**
A Saturn V rocket launched the mission from the Kennedy Space Center in America. About two hours after leaving Earth the Lunar Command and Landing Modules separated from the main rocket. 3 days later the crew entered Lunar Orbit (orbit around the moon). A day later the Landing section or Apollo Lunar Module separated from the command module. The Landing Module landed safely on the moon with Neil Armstrong and Buzz Aldrin aboard. During the landing there were several problems with the mission computer and to avoid a crash Armstrong had to take manual control of the landing craft. They eventually landed with only 25 seconds of fuel left.

**Apollo 11 Introduction**
Apollo 11 was the first mission organized to send people to the moon. It launched on July 16, 1969, carrying three astronauts Neil Armstrong, Buzz Aldrin and Michael Collins. On July 20 1969 Armstrong and Aldrin became the first humans to land on the moon successfully while Collins flew above them. The mission fulfilled the challenge John F. Kennedy made in 1961 to "land a man on the moon, and return him safely to the Earth", before the 1960s ended.

**Comment by petergault** [comment]
http://sentenceshuffle.com/#/exercise/RanqXCapI7

http://sentenceshuffle.com/#/exercise/CViWKEnkYu

http://sentenceshuffle.com/#/exercise/9ZyO3eNAXa

**Comment by petergault** [comment]
_Notes on Activity Types:_
In particular, it seems like Sentence Shuffle could be a great activity for having students re-construct the timeline of a story. For example, we could quickly put together this activity: http://sentenceshuffle.com/#/exercise/gPf2qxpYU2

Another great use case is any historical exploration, such as Lewis and Clark or Apollo 11: 
http://sentenceshuffle.com/#/exercise/gPf2qxpYU2

We're now going to test a few scientific activities such as Mitosis. It'd be great if you could follow along in the Github issue tracker.
