### ISSUE TITLE
Teacher Feedback Guide

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#7]
We can go through all of the emails we have received from teachers over the last four months and see which features they are asking for. We need to make sure these features make it into the scorebook update (for example, deleting units). 

The goal here is to put together a google doc that outlines all of the important features we are missing. 

Feedback Index here: https://docs.google.com/spreadsheets/d/1VnPNinkE6h2lHiiW36up_fEORu_O2zq8HQ2spaWRlG8/edit?usp=sharing

**Comment by RyanNovas** [comment]
Deleting classes and units, and changing class codes are three very big ones.

**Comment by petergault** [comment]
2/3 are done. We don't have deleting units built into the workflow, not sure where that should go.

**Comment by RyanNovas** [comment]
I have had requests for "co-teachers" to be able to manage classroom too. Would it be possible for two accounts to share the teacher role?
