### ISSUE TITLE
Bill Proofreading Review

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#8]
Have Bill review our new stories, dive into the grammar.

**Comment by RyanNovas** [comment]
I've emailed Bill asking him to proofread. Awaiting his response.

**Comment by RyanNovas** [comment]
Bill's proofread Summative Assessment #1 with parentheses.

**Comment by petergault** [comment]
Keep this open until the edits have been pushed to the server. If there are no edits, then re-close.

**Comment by RyanNovas** [comment]
Pushed before closing.
